# Generated by Django 6.1.1 on 2026-09-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('general', 'General Physician'), ('carddiology', 'cardiology'), ('neurology', 'Neurology')], default='general', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
