# Generated by Django 6.1.1 on 2026-09-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='M', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('severity', models.IntegerField(choices=[(1, 'Critical'), (2, 'Serious'), (3, 'Mild'), (4, 'Minor')], default=3)),
            ],
        ),
    ]
