# Generated by Django 6.1.1 on 2026-09-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient',
            new_name='patient',
        ),
    ]
